# Schema for the configuration files of the Name day module.

nameday.settings:
  type: config_object
  label: 'Name day settings'
  mapping:
    show_date:
      type: boolean
      label: 'Show date in the name day'
    show_holiday:
      type: boolean
      label: 'Show holiday in the name day, if any'
    date_format:
      type: string
      label: 'Date format'
    date_format_custom:
      type: string
      label: 'Custom date format'
